### ISSUE TITLE
Assertation Error in training 

### ISSUE THREAD

**Issue by raiyan24r** [wvangansbeke/LaneDetection_End2End#90]
Running the command throws this error in google colab
How do I solve this ?
```
Traceback (most recent call last):
  File "main.py", line 523, in <module>
    main()
  File "main.py", line 71, in main
    split_percentage=args.split_percentage)
  File "/content/drive/My Drive/Colab-Notebooks/end2end/Birds_Eye_View_Loss/Dataloader/Load_Data_new.py", line 316, in get_loader
    resize=resize)
  File "/content/drive/My Drive/Colab-Notebooks/end2end/Birds_Eye_View_Loss/Dataloader/Load_Data_new.py", line 51, in __init__
    assert len(self.rgb_lst) == len(self.gt_lst) == 2535
AssertionError
```

**Comment by raiyan24r** [comment]
I also tried changing the number to the size of my dataset, same issue

**Comment by Arjun-123a** [comment]
Changing the value to 2535 gave me out of index error.

`size train loader is 2901
size valid loader is 725
Traceback (most recent call last):
  File "/content/drive/MyDrive/LaneDetection_E2E/Backprojection_Loss/main.py", line 548, in <module>
    main()
  File "/content/drive/MyDrive/LaneDetection_E2E/Backprojection_Loss/main.py", line 89, in main
    split_percentage=args.split_percentage)
  File "/content/drive/MyDrive/LaneDetection_E2E/Backprojection_Loss/Dataloader/Load_Data_new.py", line 280, in get_loader
    nclasses=nclasses)
  File "/content/drive/MyDrive/LaneDetection_E2E/Backprojection_Loss/Dataloader/Load_Data_new.py", line 98, in __init__
    self.valid_idx = [target_idx[i]-1 for i in valid_idx]
  File "/content/drive/MyDrive/LaneDetection_E2E/Backprojection_Loss/Dataloader/Load_Data_new.py", line 98, in <listcomp>
    self.valid_idx = [target_idx[i]-1 for i in valid_idx]
IndexError: list index out of range`

I have downloaded the dataset from the link specified in the README.
